### ISSUE TITLE
Feature request: selfhosted gitea repo

### ISSUE THREAD

**Issue by Ed1ks** [project-idx/templates#10]
Hello,

please allow "Import a repo" with selfhosted git repositorys.
If I choose an template to run a project, I can clone the repo. But it creates a seperate directory, which is not the workdir and so the preview and extension like nuxtr dont work.

![image](https://github.com/user-attachments/assets/5377c859-ca9b-4536-a1ec-1a49945e1be6)

Thank you.

**Comment by romannurik** [comment]
Hi there! Mind dropping this into our [feature request portal](https://idx.uservoice.com/)?

**Comment by rodydavis** [comment]
Have you tried creating a blank workspace and cloning the repo from the command line?
