### ISSUE TITLE
Issue update: Emulator camera does not work properly in flutter apps.

### ISSUE THREAD

**Issue by Mr-Nithil** [project-idx/templates#11]
I'm working on a flutter app which use the emulator camera. But in the project-idx imulator it does not work properly. It is difficult to use the emulator camera for the camera related feature testing and development. 

![Screenshot 2024-09-02 142734](https://github.com/user-attachments/assets/aaa263e4-a7e5-472e-9ea7-6ae79c480906)

**Comment by davideast** [comment]
Hey @Mr-Nithil! Can you post this issue in https://idx.community.dev?

**Comment by Mr-Nithil** [comment]
@davideast does it fixed or I cannot reach the given link....
